version: "3.9"

services:
  cvooster_be_service:
    build:
      context: ./cvooster-be-service
      dockerfile: Dockerfile 
    ports:
      - "8000:8000" 
    volumes:
      - ./cvooster-be-service:/cvooster-be-service       
    depends_on:
      - db          

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cvooster_psql
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

  cvooster_fe_app:
    build:
      context: ./cvooster-fe-app
      dockerfile: Dockerfile 
    ports:
      - "3000:3000" 
    volumes:
      - ./cvooster-fe-app:/cvooster-fe-app
    depends_on:
      - web

volumes:
  pgdata:
